// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtsmNrKWA4ZpW4kW6s7R2N4tnYLIBbEGg',
    appId: '1:497924551481:web:003972c836d245692b6ee8',
    messagingSenderId: '497924551481',
    projectId: 'pylearner-6d57d',
    authDomain: 'pylearner-6d57d.firebaseapp.com',
    storageBucket: 'pylearner-6d57d.appspot.com',
    measurementId: 'G-02BNC48ZYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGMBYFaUahz9TLjOZlQ__19VkVr6JMNtk',
    appId: '1:497924551481:android:1b1fd271e422fda92b6ee8',
    messagingSenderId: '497924551481',
    projectId: 'pylearner-6d57d',
    storageBucket: 'pylearner-6d57d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtLCF0iAoOUTAGWOMwUwykvbNyi1p6XAk',
    appId: '1:497924551481:ios:ef6a0c9f4fd1d5672b6ee8',
    messagingSenderId: '497924551481',
    projectId: 'pylearner-6d57d',
    storageBucket: 'pylearner-6d57d.appspot.com',
    iosBundleId: 'com.example.pyLearner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtLCF0iAoOUTAGWOMwUwykvbNyi1p6XAk',
    appId: '1:497924551481:ios:ef6a0c9f4fd1d5672b6ee8',
    messagingSenderId: '497924551481',
    projectId: 'pylearner-6d57d',
    storageBucket: 'pylearner-6d57d.appspot.com',
    iosBundleId: 'com.example.pyLearner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtsmNrKWA4ZpW4kW6s7R2N4tnYLIBbEGg',
    appId: '1:497924551481:web:abbbb6dca8988f572b6ee8',
    messagingSenderId: '497924551481',
    projectId: 'pylearner-6d57d',
    authDomain: 'pylearner-6d57d.firebaseapp.com',
    storageBucket: 'pylearner-6d57d.appspot.com',
    measurementId: 'G-1FMN6PL9YQ',
  );
}
